server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mambo-wang/springcloudlearning-config-repo    # 配置Git仓库的地址
          username: mambo-wang                                                         # Git仓库的账号
          password: wangbao1991                                                         # Git仓库的密码
        health:
          repositories:
            a-foo:
              label: config-label-v2.0
              name: microservice-foo
              profiles: dev
          enabled: true
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    org.springframework.cloud: debug #调整为debug能更清楚地看到请求git配置文件的过程
    org.springframework.boot: debug