server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mambo-wang/springcloudlearning-config-repo.git    # 配置Git仓库的地址
          username: mambo-wang                                                         # Git仓库的账号
          password: wangbao1991                                                         # Git仓库的密码