eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8010
spring:
  application:
    name: service-ribbon-hystrix-turbine-mq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest