eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8021
spring:
  application:
    name: service-mambo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  data:
    jpa:
      repositories:
        enabled: true
feign:
  hystrix:
    enabled: true
