eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8022
spring:
  application:
    name: mambo
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
